Naming/VariableNumber:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
